before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: RYj8IZ/MxR/SFaKQMC9s94+n+fikPJhfWMgei9XIsNCtiCbg/xQIPSBZwPK4xcRvlAhM/CwB7ifkqjWbbPeDmR6VhKqK1db0dBjnDVuJaqibT0ap3dUTC0mqb2AXTWnEiIT2lcGL5myzU0vhoKN+D0QZ39DXt/Ejeuj/RKsLw9N+inYMwu/77KftliQdqwxkB6ElDBVrTahtGogZ2/kAv4bebeiLBRxLz7B7QtEU6WCdjR0p59SIAmZsr3L4Q/+lYV1QBY9UmOTGnZUMR7AkNRnXFwEtuuihyg8goyEO32nTBNfH7h12vFvFet+hbccMppEca1pD1UUJZVHgzfy+lLKmZ3gG++fDEFmNnsIvz09VTyifRAmvuUsuk5umuw++wlsB8XisjI9Dx0/Io9X7rEjqMTm3reWNJ7h+CRFN8S9mAqQSYsAgfQvoeNI+a5IEFzcu1V7SFD9qTGNCr5HGBrJXZVeExBGxKWwmyBYT9LJPE++E3wzSe9NCMloNws+xN0FY89NYIg44wLGmb+Jy3rDRvCyMtmsqwKMvFUXUr3fh/p6e7AQ7JPUn0DBLezJ9HLpCjX0nUVU62FhHCOm7OPPZ8gFC5WaJaUD/rGu3R9HYuyta0RDQ0c/e6boUUs9jv22oXa4CHON6eMjU9VqJyZu6VxIqf6aNK4QBf2ueL8g= # CRYPTO_AES_KEY
language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
